"""
Order and payment status constants.

Using string constants keeps the DB simple; enums can be added later.
"""

# --- Order lifecycle (delivery flow) ---
ORDER_STATUS_PENDING = "pending"
ORDER_STATUS_CONFIRMED = "confirmed"
ORDER_STATUS_PREPARING = "preparing"
ORDER_STATUS_PICKED_UP = "picked_up"
ORDER_STATUS_ON_THE_WAY = "on_the_way"
ORDER_STATUS_DELIVERED = "delivered"
ORDER_STATUS_CANCELLED = "cancelled"

ORDER_STATUSES = {
    ORDER_STATUS_PENDING,
    ORDER_STATUS_CONFIRMED,
    ORDER_STATUS_PREPARING,
    ORDER_STATUS_PICKED_UP,
    ORDER_STATUS_ON_THE_WAY,
    ORDER_STATUS_DELIVERED,
    ORDER_STATUS_CANCELLED,
}

# Allowed status transitions (restaurant owner updates)
ORDER_STATUS_TRANSITIONS: dict[str, set[str]] = {
    ORDER_STATUS_PENDING: {ORDER_STATUS_CONFIRMED, ORDER_STATUS_CANCELLED},
    ORDER_STATUS_CONFIRMED: {ORDER_STATUS_PREPARING, ORDER_STATUS_CANCELLED},
    ORDER_STATUS_PREPARING: {ORDER_STATUS_PICKED_UP, ORDER_STATUS_CANCELLED},
    ORDER_STATUS_PICKED_UP: {ORDER_STATUS_ON_THE_WAY, ORDER_STATUS_CANCELLED},
    ORDER_STATUS_ON_THE_WAY: {ORDER_STATUS_DELIVERED, ORDER_STATUS_CANCELLED},
    ORDER_STATUS_DELIVERED: set(),
    ORDER_STATUS_CANCELLED: set(),
}

# --- Payment (mock flow for now — no Stripe yet) ---
PAYMENT_STATUS_PENDING = "pending"
PAYMENT_STATUS_PAID = "paid"
PAYMENT_STATUS_FAILED = "failed"

PAYMENT_STATUSES = {
    PAYMENT_STATUS_PENDING,
    PAYMENT_STATUS_PAID,
    PAYMENT_STATUS_FAILED,
}
